map $http_user_agent $bad_bot {
  default 0;

  "~*ia_archiver"          1;
  "~*archive\.org_bot"     1;
  "~*archive\.today"       1;
  "~*Wayback"              1;
  "~*heritrix"             1;

  "~*nikto"                1;
  "~*sqlmap"               1;
  "~*nmap"                 1;
  "~*masscan"              1;
  "~*nessus"               1;
  "~*openvas"              1;
  "~*acunetix"             1;
  "~*nuclei"               1;
  "~*WPScan"               1;
  "~*ZmEu"                 1;
  "~*dirbuster"            1;
  "~*gobuster"             1;
  "~*wpscan"               1;
  "~*x09x09x09"            1;

  "~*SemrushBot"           1;
  "~*AhrefsBot"            1;
  "~*MJ12bot"              1;
  "~*DotBot"               1;
  "~*BLEXBot"              1;
  "~*DataForSeoBot"        1;
  "~*PetalBot"             1;
  "~*SeznamBot"            1;
  "~*Barkrowler"           1;
  "~*serpstatbot"          1;
  "~*ZoominfoBot"          1;
  "~*MegaIndex"            1;
  "~*Yandex"               1;

  "~*libwww-perl"          1;
  "~*python-requests"      1;
  ""                       1;
}
