#!/usr/bin/env bun

import { snapshot } from '../lib/snapshot';

const SOURCES = {
  ROBOTS_WEB_TEMPLATE: 'well-known/robots.web.txt',
  LLMS_WEB_TEMPLATE: 'well-known/llms.web.md',
  SECURITY_TEMPLATE: 'well-known/security.txt',
} as const;

const OUT = 'apps/web/src/lib/generated/well-known/well-known.gen.ts';

const HEADER = [
  '// Generated by scripts/well-known/generate.ts from well-known/*.',
  '// Do not edit. Run: bun run well-known:generate',
  '',
  '',
].join('\n');

const escape = (content: string): string =>
  content
    .replaceAll('\\', String.raw`\\`)
    .replaceAll('`', String.raw`\``)
    .replaceAll('${', '\\${');

const entries = await Promise.all(
  Object.entries(SOURCES).map(
    async ([name, path]) => `export const ${name} = \`${escape(await Bun.file(path).text())}\`;`
  )
);

const rendered = `${HEADER}${entries.join('\n\n')}\n`;

process.exit(
  await snapshot({
    out: OUT,
    rendered,
    summary: 'llms.txt / robots.txt / security.txt templates for the web app',
    remedy: ['Run: bun run well-known:generate, then review the diff.'],
    check: process.argv.includes('--check'),
  })
);
