#!/usr/bin/env bun

import openapiTS, { astToString } from 'openapi-typescript';

import { snapshot } from '../lib/snapshot';

import type { OpenAPI3 } from 'openapi-typescript';

const SPEC = 'apps/api/generated/openapi/openapi.json';
const OUT = 'apps/web/src/lib/generated/openapi/schema.gen.ts';

const HEADER = [
  '// Generated by scripts/openapi/types.ts from apps/api/generated/openapi/openapi.json.',
  '// Do not edit. Run: bun run openapi:types',
  '',
  '',
].join('\n');

const spec = (await Bun.file(SPEC).json()) as OpenAPI3;
const rendered = `${HEADER}${astToString(await openapiTS(spec))}`;

process.exit(
  await snapshot({
    out: OUT,
    rendered,
    summary: `types for ${SPEC}`,
    remedy: ['Run: bun run openapi:types, then review the diff.'],
    check: process.argv.includes('--check'),
  })
);
