#!/usr/bin/env bun

import { API_KEY_HEADER, API_V1_PREFIX, DEV_API_PORT, PROD_API_URL } from '@qafiyah/config';

import { snapshot } from '../lib/snapshot';

type Row = { readonly name: string; readonly slug: string; readonly poemsCount: number };

type Resource = { readonly path: string; readonly exportName: string };

const RESOURCES: readonly Resource[] = [
  { path: '/eras', exportName: 'erasOptions' },
  { path: '/meters', exportName: 'metersOptions' },
  { path: '/rhymes', exportName: 'rhymesOptions' },
  { path: '/themes', exportName: 'themesOptions' },
  { path: '/collections', exportName: 'collectionsOptions' },
];

const OUT = 'apps/web/src/lib/generated/taxonomy/taxonomy-options.gen.ts';
const RETRY_ATTEMPTS = 3;
const RETRY_DELAY_MS = 1000;

const target = process.argv.includes('--dev') ? 'dev' : 'prod';
const base =
  target === 'dev'
    ? `http://localhost:${DEV_API_PORT}${API_V1_PREFIX}`
    : `${PROD_API_URL}${API_V1_PREFIX}`;
const apiKey = process.env['TAXONOMY_API_KEY'] ?? process.env['API_KEY_FULL'];

async function fetchRows(path: string): Promise<readonly Row[]> {
  let lastError = '';
  for (let attempt = 1; attempt <= RETRY_ATTEMPTS; attempt++) {
    const res = await fetch(`${base}${path}`, {
      headers: apiKey ? { [API_KEY_HEADER]: apiKey } : {},
    }).catch((cause) => cause as Error);
    if (!(res instanceof Error) && res.ok) {
      const body = (await res.json()) as { data: readonly Row[] };
      return body.data;
    }
    lastError = res instanceof Error ? res.message : `HTTP ${res.status}`;
    if (attempt < RETRY_ATTEMPTS) await Bun.sleep(RETRY_DELAY_MS * attempt);
  }
  throw new Error(`GET ${path} failed after ${RETRY_ATTEMPTS} attempts: ${lastError}`);
}

const HEADER = [
  '// Generated by scripts/taxonomy/generate.ts from the live API.',
  '// Do not edit. Run: bun run taxonomy:generate',
  '',
  '',
].join('\n');

const quote = (value: string): string =>
  `'${value.replaceAll('\\', String.raw`\\`).replaceAll("'", "\\'")}'`;

function renderOptions(rows: readonly Row[]): string {
  if (rows.length === 0) return '[]';
  const entries = rows
    .map(
      (row) =>
        `  { value: ${quote(row.slug)}, label: ${quote(row.name)}, poemsCount: ${row.poemsCount} },`
    )
    .join('\n');
  return `[\n${entries}\n]`;
}

const sections = await Promise.all(
  RESOURCES.map(async (resource) => {
    const rows = await fetchRows(resource.path);
    return `export const ${resource.exportName}: readonly SelectOption[] = ${renderOptions(rows)};`;
  })
);

const rendered = `${HEADER}import type { SelectOption } from '@/lib/constants/taxonomy-data';\n\n${sections.join('\n\n')}\n`;

process.exit(
  await snapshot({
    out: OUT,
    rendered,
    summary: `taxonomy filter options from ${base}`,
    remedy: ['Run: bun run taxonomy:generate, then review the diff.'],
    check: process.argv.includes('--check'),
  })
);
